// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SwiftDataFlashCardSample",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "FlashCard",
            targets: ["FlashCard"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "End/FlashCard/Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "FlashCard",
            path: "End/FlashCard"
        )
    ]
)
